import type { Tour } from 'nextstepjs';

export const onboardingSteps: any[] = [
  {
    tour: "onboardingTour",
    steps: [
      {
        icon: "👋",
        title: "Welcome to RSVP Reader!",
        content: "We're excited to have you here! Let us quickly show you around so you can start speed reading right away.",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
      },
      {
        icon: "📚",
        title: "Your First Book",
        content: "We've added a sample book to your library so you can try out speed reading immediately.",
        selector: "#onboarding-sample-book",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        disableInteraction: true,
      },
      {
        icon: "▶️",
        title: "Start Reading",
        content: "Click this button to begin reading. The text will be displayed one word at a time.",
        selector: "#onboarding-start-reading",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        hideNext: true,
        disableInteraction: false,
      },
      {
        icon: "⏯️",
        title: "Play & Pause",
        content: "Use this button (or Space) to start or pause reading at any time.",
        selector: "#onboarding-play-pause",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        hideNext: true,
        disableInteraction: false,
      },
      {
        icon: "⏪",
        title: "Skip Back",
        content: "Need to re-read something? Skip back 10 words with this button or Left Arrow.",
        selector: "#onboarding-skip-back",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        hideNext: true,
        disableInteraction: false,
      },
      {
        icon: "⏩",
        title: "Skip Forward",
        content: "Want to skip ahead? Move forward 10 words with this button or Right Arrow.",
        selector: "#onboarding-skip-forward",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        hideNext: true,
        disableInteraction: false,
      },
      {
        icon: "🔄",
        title: "Restart",
        content: "Started losing focus? Restart from the beginning or use the 'R' key.",
        selector: "#onboarding-reset",
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        hideNext: true,
        disableInteraction: false,
      },
      {
        icon: "⚙️",
        title: "Settings",
        content: "Customize your reading speed, font size, and more here!",
        selector: "#onboarding-settings",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        hideNext: true,
        disableInteraction: false,
      },
      {
        icon: "✨",
        title: "Premium Features",
        content: "In settings, you can see your current limits. Upgrade to Premium for up to 1000 WPM and more customization!",
        selector: "#onboarding-premium-info",
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 20,
        disableInteraction: false,
      },
      {
        icon: "🎉",
        title: "You're All Set!",
        content: "Enjoy your speed reading journey! You can always upload your own texts too.",
        side: "bottom",
        showControls: true,
        showSkip: false,
        pointerPadding: 20,
      },
    ],
  },
];
